### ISSUE TITLE
Metrics.Net failed start up caused ASP.Net application pools to turn into zombies.

### ISSUE THREAD

**Issue by eezewski** [etishor/Metrics.NET#67]
Hey Iulian,

I ran into this error with one of our asp.net websites:

```2015-03-04 21:10:55,969 [7] ERROR Metrics.MetricsConfig [(null)] - Metrics: error configuring HttpListener
System.Net.HttpListenerException (0x80004005): Failed to listen on prefix 'http://+:1234/EmailGatewaySendGridEvents/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Metrics.Visualization.MetricsHttpListener.Start() in c:\Users\eti\Work\Metrics.NET\Src\Metrics\Visualization\MetricsHttpListener.cs:line 51
   at Metrics.MetricsConfig.WithHttpEndpoint(String httpUriPrefix) in c:\Users\eti\Work\Metrics.NET\Src\Metrics\MetricsConfig.cs:line 62
   at Metrics.MetricsConfig.ConfigureHttpListener() in c:\Users\eti\Work\Metrics.NET\Src\Metrics\MetricsConfig.cs:line 203```

It caused our application pool to go into a strange zombie state where the endpoint would throw 500 errors with this message in it, but not actually crash the application pool so that it could be restarted. Once we stopped and restarted the pool operation returned to normal and I am unable to replicate the issue.

I would appreciate if you could look into this.

Evan

**Comment by etishor** [comment]
The message " Failed to listen on prefix 'http://+:1234/EmailGatewaySendGridEvents/' because it conflicts with an existing registration on the machine" would suggest that there is something else listening on the same prefix. I'm not sure if this is even possible, but maybe the application pool is being recycled and the new instance is brought up before the old one is completely disposed and the old one is still listening on the same prefix. Or maybe http.sys does not release the prefix instantly... i'll have to check. 

I'll try to see if I can reproduce the issue as I would really like MetricsHttpListener to be as resilient to failure as possible.

Another suggestion - since you are using asp.net - if you are using OWIN, take a look at the OWIN adapter as it contains a middlewere for serving the metrics which can be used instead of the HttpListener one. 

All the best,
Iulian

**Comment by etishor** [comment]
This [commit](https://github.com/etishor/Metrics.NET/commit/1b6fc94310a818f5c03fb5a6a6172863c204e9ab) should improve the situation when running under apppools that get recycled. 

The fix is on nuget in the latest version.
