### ISSUE TITLE
Accepted way of "rolling" perf counters?

### ISSUE THREAD

**Issue by rapoth** [etishor/Metrics.NET#82]
This is a fantastic project! I'm wondering what is the suggested way for rolling perf counter data. For instance, if you look at [Serilog](https://github.com/serilog/serilog/wiki/Configuration-Basics), there is a provision for providing a date format using which the perf files are rolled. This makes it very easy to implement retention policies (e.g., retain only the last 3 days worth of perf data). 

What are your thoughts on this?

**Comment by etishor** [comment]
@rapoth I'm assuming you are referring to the CSV metrics that get written to a file. For that there is no support for rolling files. 

There is an implementation using NLog for logging the metrics - and NLog can write to rolling files - but it is not in the core package because of the dependency on NLog and not published to nuget because it is not tested/used. Take a look at the [NLog Adapter](https://github.com/etishor/Metrics.NET/tree/master/Src/Adapters/Metrics.NLog) for more information.

**Comment by rapoth** [comment]
@etishor Thanks Iulian! I'll check this out.
