### ISSUE TITLE
Statsd support

### ISSUE THREAD

**Issue by stephanstapel** [etishor/Metrics.NET#93]
Hi,

Your library was just recommended by a friend and I must say that it's great that you ported Metrics to .net. Thanks a lot!

I saw this: https://github.com/etishor/Metrics.NET/issues/8 
and wondered if you could share the existing statsd code.

Cheers,

Stephan

**Comment by etishor** [comment]
@stephanstapel I have no statsd integration code. The un-pushed code I mentioned was the graphite integration.

I don't personally use statsd so I don't know much about it. It should not be very complicated to extend the metrics.net library to push data from metrics directly to statsd - at least in a basic form. Pushing it efficiently might be a bit more challenging. 

If you don't already have apps & infrastructure already using statsd it does not make a lot of sense to push data to statsd so that it gets pushed to graphite/influxdb. You can push it directly from metrics.net.

**Comment by stephanstapel** [comment]
I tried InfluxDB and really like it, thanks a lot. Do you plan to support InfluxDB 0.9 anytime soon?

**Comment by guydou** [comment]
@etishor I think that one of the benefits of using statsd instead of reporting directly to Graphite/InfluxDB is the decouple of the reporting from the code, 
If we want to add a reporting target it is much easier and less dangrous to add it to the Statsd instead of to the application. 

I have use cases that require we to send the reporting data to several places, and I think that handeling the targets in the Statsd is better. 

I will look into the code, and try to see if I can add Statsd support
